In [3]:
# Implement graph ADT   Undirected Graph Implementation
import numpy as np
                          
class Graph:
    def __init__(self, vertices):
        self._vertices = vertices
        self._adjmat = np.zeros((vertices, vertices))
        
    def insert_edge(self, u, v, x=1):
        self._adjmat[u][v] = x  # x= cost/weight
        
    def remove_edge(self, u, v):
        self._adjmat[u][v] = 0 # assign 0 to remove
        
    def exist_edge(self, u, v):
        return self._adjmat[u][v] != 0
    
    def vertex_count(self):
        return self._vertices
    
    def edge_count(self):
        count = 0
        for i in range(self._vertices):
            for j in range(self._vertices):
                if self._adjmat[i][j] != 0:
                    count = count + 1
        return count
    
    def vertices(self):
        for i in range(self._vertices):
            print(i,end=" ")
        print()
        
    def edges(self):
        for i in range(self._vertices):
            for j in range(self._vertices):
                if self._adjmat[i][j] != 0:
                    print(i,"--",j)
                    
    def outdegree(self,v):
        count = 0
        for j in range(self._vertices):
                if self._adjmat[v][j] != 0:
                    count = count + 1
        return count
    
    def indegree(self, v):
        count =0
        for i in range(self._vertices):
            if self._adjmat[i][v] != 0:
                count = count+1
        return count
    
    def display_adjmat(self):
        print(self._adjmat)
        
# Undirected Graph

G = Graph(4)     # 4 nodes so 4*4 matrix
G.display_adjmat()
print("vertices:",G.vertex_count())
print("edges:",G.edge_count())

                    
        
    
    
        
        

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
vertices: 4
edges: 0


In [6]:
G.insert_edge(0,1)
G.insert_edge(0,2)
G.insert_edge(1,0)
G.insert_edge(1,2)
G.insert_edge(2,0)
G.insert_edge(2,1)
G.insert_edge(2,3)
G.insert_edge(3,2)
G.display_adjmat()
print("vertices:",G.vertex_count())
print("edges:",G.edge_count())


[[0. 1. 1. 0.]
 [1. 0. 1. 0.]
 [1. 1. 0. 1.]
 [0. 0. 1. 0.]]
vertices: 4
edges: 8


In [7]:
G.edges()

0 -- 1
0 -- 2
1 -- 0
1 -- 2
2 -- 0
2 -- 1
2 -- 3
3 -- 2


In [11]:
print("edge between 3 and 1 ? ",G.exist_edge(3,1))

edge between 3 and 1 ?  False


In [12]:
print("Degree",G.indegree(2))

Degree 3


In [13]:
G.remove_edge(1,2)

In [14]:
print("edge between 1 and 2 ? ",G.exist_edge(1,2))

edge between 1 and 2 ?  False
