In [7]:
# Implement graph ADT   Directed Graph Implementation
import numpy as np
                          
class Graph:
    def __init__(self, vertices):
        self._vertices = vertices
        self._adjmat = np.zeros((vertices, vertices))
        
    def insert_edge(self, u, v, x=1):
        self._adjmat[u][v] = x  # x= cost/weight
        
    def remove_edge(self, u, v):
        self._adjmat[u][v] = 0 # assign 0 to remove
        
    def exist_edge(self, u, v):
        return self._adjmat[u][v] != 0
    
    def vertex_count(self):
        return self._vertices
    
    def edge_count(self):
        count = 0
        for i in range(self._vertices):
            for j in range(self._vertices):
                if self._adjmat[i][j] != 0:
                    count = count + 1
        return count
    
    def vertices(self):
        for i in range(self._vertices):
            print(i,end=" ")
        print()
        
    def edges(self):
        for i in range(self._vertices):
            for j in range(self._vertices):
                if self._adjmat[i][j] != 0:
                    print(i,"--",j)
                    
    def outdegree(self,v):
        count = 0
        for j in range(self._vertices):
                if self._adjmat[v][j] != 0:
                    count = count + 1
        return count
    
    def indegree(self, v):
        count =0
        for i in range(self._vertices):
            if self._adjmat[i][v] != 0:
                count = count+1
        return count
    
    def display_adjmat(self):
        print(self._adjmat)
        
# directed Graph

G = Graph(4)     # 4 nodes so 4*4 matrix
G.display_adjmat()
print("Number of vertices:",G.vertex_count())
G.insert_edge(0,1)
G.insert_edge(0,2)
G.insert_edge(1,2)
G.insert_edge(2,3)

print("Number of edges:",G.edge_count())


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Number of vertices: 4
Number of edges: 4


In [8]:
G.edges()

0 -- 1
0 -- 2
1 -- 2
2 -- 3


In [9]:
print("edge between 3 and 1 ? ",G.exist_edge(3,1))

edge between 3 and 1 ?  False


In [11]:
print("Indegree of node 2 is :",G.indegree(2))

Indegree of node 2 is : 2


In [13]:
print("Outdegree of node 2 is :",G.outdegree(2))

Outdegree of node 2 is : 1
