In [1]:
# Implement graph ADT   Weighted Undirected Graph Implementation
import numpy as np
                          
class Graph:
    def __init__(self, vertices):
        self._vertices = vertices
        self._adjmat = np.zeros((vertices, vertices))
        
    def insert_edge(self, u, v, x=1):
        self._adjmat[u][v] = x  # x= cost/weight
        
    def remove_edge(self, u, v):
        self._adjmat[u][v] = 0 # assign 0 to remove
        
    def exist_edge(self, u, v):
        return self._adjmat[u][v] != 0
    
    def vertex_count(self):
        return self._vertices
    
    def edge_count(self):
        count = 0
        for i in range(self._vertices):
            for j in range(self._vertices):
                if self._adjmat[i][j] != 0:
                    count = count + 1
        return count
    
    def vertices(self):
        for i in range(self._vertices):
            print(i,end=" ")
        print()
        
    def edges(self):
        for i in range(self._vertices):
            for j in range(self._vertices):
                if self._adjmat[i][j] != 0:
                    print(i,"--",j)
                    
    def outdegree(self,v):
        count = 0
        for j in range(self._vertices):
                if self._adjmat[v][j] != 0:
                    count = count + 1
        return count
    
    def indegree(self, v):
        count =0
        for i in range(self._vertices):
            if self._adjmat[i][v] != 0:
                count = count+1
        return count
    
    def display_adjmat(self):
        print(self._adjmat)
        
# Weighted Undirected Graph

G = Graph(4)     # 4 nodes so 4*4 matrix
G.display_adjmat()
print("vertices:",G.vertex_count())
print("edges:",G.edge_count())

                    

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
vertices: 4
edges: 0


In [2]:
G.insert_edge(0,1,26)
G.insert_edge(0,2,16)
G.insert_edge(1,0,26)
G.insert_edge(1,2,12)
G.insert_edge(2,0,16)
G.insert_edge(2,1,12)
G.insert_edge(2,3,8)
G.insert_edge(3,2,8)
G.display_adjmat()
print("vertices:",G.vertex_count())
print("edges:",G.edge_count())


[[ 0. 26. 16.  0.]
 [26.  0. 12.  0.]
 [16. 12.  0.  8.]
 [ 0.  0.  8.  0.]]
vertices: 4
edges: 8


In [3]:
G.edges()

0 -- 1
0 -- 2
1 -- 0
1 -- 2
2 -- 0
2 -- 1
2 -- 3
3 -- 2


In [4]:
print("edge between 3 and 1 ? ",G.exist_edge(3,1))

edge between 3 and 1 ?  False


In [5]:

print("Degree",G.indegree(2))

Degree 3


In [6]:
G.remove_edge(1,2)

In [7]:
print("edge between 1 and 2 ? ",G.exist_edge(1,2))

edge between 1 and 2 ?  False
